

[[book]]
title = "A Designer's guide to Instrumentation Amplifiers"
author = "Analog Devices or Texas Instruments"
year = "Unknown"
status = "Read"
notes = "Comprehensive guide to instrumentation amplifier design."