# Semiconductors Books Metadata

[[book]]
title = "The Intel Trinity: How Robert Noyce, Gordon Moore, and Andy Grove Built the World's Most Important Company"
author = "Michael S. Malone"
year = "2014"
status = "To Read"
notes = ""

[[book]]
title = "Chip War: The Fight for the World's Most Critical Technology"
author = "Chris Miller"
year = "2022"
status = "To Read"
notes = ""

[[book]]
title = "Fabless: The Transformation of the Semiconductor Industry"
author = "Daniel Nenni, Paul McLellan"
year = "2013"
status = "To Read"
notes = ""

[[book]]
title = "Makers of the Microchip: A Documentary History of Fairchild Semiconductor"
author = "Christophe Lécuyer, David C. Brock"
year = "2010"
status = "To Read"
notes = ""

[[book]]
title = "The Chip: How Two Americans Invented the Microchip and Launched a Revolution"
author = "T.R. Reid"
year = "1984"
status = "To Read"
notes = ""

[[book]]
title = "Moore's Law: The Life of Gordon Moore, Silicon Valley's Quiet Revolutionary"
author = "Arnold Thackray, David C. Brock, Rachel Jones"
year = "2015"
status = "To Read"
notes = ""

[[book]]
title = "The Idea Factory: Bell Labs and the Great Age of American Innovation"
author = "Jon Gertner"
year = "2012"
status = "To Read"
notes = ""

[[book]]
title = "Tiger Technology: The Creation of a Semiconductor Industry in East Asia"
author = "Daniel I. Okimoto, Takuo Sugano"
year = "1999"
status = "To Read"
notes = ""

[[book]]
title = "Inside Intel: Andy Grove and the Rise of the World's Most Powerful Chip Company"
author = "Tim Jackson"
year = "1997"
status = "To Read"
notes = ""

[[book]]
title = "The Semiconductor Manufacturing Business: A Comprehensive Guide"
author = "Robert N. Noyce, Michael S. Malone"
year = "Unknown"
status = "To Read"
notes = ""

