[[book]]
title = "Superintelligence"
author = "Nick Bostrom"
year = "2014"
status = "To Read"
notes = "Explores the future of artificial intelligence and its impact on humanity."

[[book]]
title = "Shoe Dog"
author = "Phil Knight"
year = "2016"
status = "To Read"
notes = "Memoir by the creator of Nike."

[[book]]
title = "Zero to One"
author = "Peter Thiel"
year = "2014"
status = "Read"
notes = "Insights on startups and building the future."